import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

//Creates Seed Data
async function main() {
  const createCarriers = await prisma.carrier.createMany({
    data: [
      { carrierName: "XPO" },
      { carrierName: "CTS" },
      { carrierName: "Dart" },
      { carrierName: "Transport Design" },
      { carrierName: "DRT" },
      { carrierName: "Waletich" },
      { carrierName: "Taylor" },
      { carrierName: "Terminal" },
      { carrierName: "Trucking Proz" },
      { carrierName: "UTS" },
      { carrierName: "J&R" },
      { carrierName: "Kuehl" },
      { carrierName: "American Fast Freight" },
      { carrierName: "Ryder" },
      { carrierName: "Keene’s" },
      { carrierName: "XPO Logistics" },
    ],
  });

  const createCategories = await prisma.category.createMany({
    data: [
      { categoryName: "Bays", color: "blue-500" },
      { categoryName: "Completed", color: "green-500" },
      { categoryName: "Dunnage", color: "blue-500" },
      { categoryName: "Empties for Shipping", color: "gray-500" },
      { categoryName: "In Process", color: "yellow-500" },
      { categoryName: "Patio Trailers", color: "yellow-600" },
      { categoryName: "Receiving", color: "purple-400" },
      { categoryName: "Receiving - Rush", color: "pink-600" },
      { categoryName: "Receiving - Storage", color: "blue-900" },
      { categoryName: "Storage/Misc. Shipping Trailers", color: "blue-300" },
      { categoryName: "Supermarket/Legacy/Eng", color: "blue-500" },
      { categoryName: "Do Not Use", color: "red-500" },
    ],
  });

  const createPlant = await prisma.plant.create({
    data: {
      name: "RbA",
    },
  });

  const createDocks = await prisma.dock.createMany({
    data: [{ name: "RVAC" }, { name: "RMAN" }],
  });

  const createLots = await prisma.lot.createMany({
    data: [{ name: "Secondary" }],
  });

  const createViews = await prisma.view.createMany({
    data: [
      { name: "RVAC", plantId: 1, dockId: 1 },
      { name: "RMAN", plantId: 1, dockId: 2, lotId: 1 },
    ],
  });

  const createSpots = await prisma.spots.createMany({
    data: [
      { name: "50", dockId: 1 },
      { name: "49", dockId: 1 },
      { name: "48", dockId: 1 },
      { name: "47", dockId: 1 },
      { name: "46", dockId: 1 },
      { name: "45", dockId: 1 },
      { name: "44", dockId: 1 },
      { name: "43", dockId: 1 },
      { name: "42", dockId: 1 },
      { name: "41", dockId: 1 },
      { name: "40", dockId: 1 },
      { name: "39", dockId: 1 },
      { name: "38", dockId: 1 },
      { name: "37", dockId: 1 },
      { name: "36", dockId: 1 },
      { name: "35", dockId: 1 },
      { name: "34", dockId: 1 },
      { name: "33", dockId: 1 },
      { name: "32", dockId: 1 },
      { name: "31", dockId: 1 },
      { name: "30", dockId: 1 },
      { name: "29", dockId: 1 },
      { name: "28", dockId: 1 },
      { name: "27", dockId: 1 },
      { name: "26", dockId: 1 },
      { name: "25", dockId: 1 },
      { name: "24", dockId: 1 },
      { name: "23", dockId: 1 },
      { name: "22", dockId: 1 },
      { name: "21", dockId: 1 },
      { name: "20", dockId: 1 },
      { name: "19", dockId: 1 },
      { name: "18", dockId: 1 },
      { name: "17", dockId: 1 },
      { name: "16", dockId: 1 },
      { name: "15", dockId: 1 },
      { name: "14", dockId: 1 },
      { name: "13", dockId: 1 },
      { name: "12", dockId: 1 },
      { name: "11", dockId: 1 },
      { name: "10", dockId: 1 },
      { name: "9", dockId: 1 },
      { name: "8", dockId: 1 },
      { name: "7", dockId: 1 },
      { name: "6", dockId: 1 },
      { name: "5", dockId: 1 },
      { name: "4", dockId: 1 },
      { name: "3", dockId: 1 },
      { name: "2", dockId: 1 },
      { name: "1", dockId: 1 },
      { name: "50", dockId: 2 },
      { name: "49", dockId: 2 },
      { name: "48", dockId: 2 },
      { name: "47", dockId: 2 },
      { name: "46", dockId: 2 },
      { name: "45", dockId: 2 },
      { name: "44", dockId: 2 },
      { name: "43", dockId: 2 },
      { name: "42", dockId: 2 },
      { name: "41", dockId: 2 },
      { name: "40", dockId: 2 },
      { name: "39", dockId: 2 },
      { name: "38", dockId: 2 },
      { name: "37", dockId: 2 },
      { name: "36", dockId: 2 },
      { name: "35", dockId: 2 },
      { name: "34", dockId: 2 },
      { name: "33", dockId: 2 },
      { name: "32", dockId: 2 },
      { name: "31", dockId: 2 },
      { name: "30", dockId: 2 },
      { name: "29", dockId: 2 },
      { name: "28", dockId: 2 },
      { name: "27", dockId: 2 },
      { name: "26", dockId: 2 },
      { name: "25", dockId: 2 },
      { name: "24", dockId: 2 },
      { name: "23", dockId: 2 },
      { name: "22", dockId: 2 },
      { name: "21", dockId: 2 },
      { name: "20", dockId: 2 },
      { name: "19", dockId: 2 },
      { name: "18", dockId: 2 },
      { name: "17", dockId: 2 },
      { name: "16", dockId: 2 },
      { name: "15", dockId: 2 },
      { name: "14", dockId: 2 },
      { name: "13", dockId: 2 },
      { name: "12", dockId: 2 },
      { name: "11", dockId: 2 },
      { name: "10", dockId: 2 },
      { name: "9", dockId: 2 },
      { name: "8", dockId: 2 },
      { name: "7", dockId: 2 },
      { name: "6", dockId: 2 },
      { name: "5", dockId: 2 },
      { name: "4", dockId: 2 },
      { name: "3", dockId: 2 },
      { name: "2", dockId: 2 },
      { name: "1", dockId: 2 },
      { name: "50", lotId: 1 },
      { name: "49", lotId: 1 },
      { name: "48", lotId: 1 },
      { name: "47", lotId: 1 },
      { name: "46", lotId: 1 },
      { name: "45", lotId: 1 },
      { name: "44", lotId: 1 },
      { name: "43", lotId: 1 },
      { name: "42", lotId: 1 },
      { name: "41", lotId: 1 },
      { name: "40", lotId: 1 },
      { name: "39", lotId: 1 },
      { name: "38", lotId: 1 },
      { name: "37", lotId: 1 },
      { name: "36", lotId: 1 },
      { name: "35", lotId: 1 },
      { name: "34", lotId: 1 },
      { name: "33", lotId: 1 },
      { name: "32", lotId: 1 },
      { name: "31", lotId: 1 },
      { name: "30", lotId: 1 },
      { name: "29", lotId: 1 },
      { name: "28", lotId: 1 },
      { name: "27", lotId: 1 },
      { name: "26", lotId: 1 },
      { name: "25", lotId: 1 },
      { name: "24", lotId: 1 },
      { name: "23", lotId: 1 },
      { name: "22", lotId: 1 },
      { name: "21", lotId: 1 },
      { name: "20", lotId: 1 },
      { name: "19", lotId: 1 },
      { name: "18", lotId: 1 },
      { name: "17", lotId: 1 },
      { name: "16", lotId: 1 },
      { name: "15", lotId: 1 },
      { name: "14", lotId: 1 },
      { name: "13", lotId: 1 },
      { name: "12", lotId: 1 },
      { name: "11", lotId: 1 },
      { name: "10", lotId: 1 },
      { name: "9", lotId: 1 },
      { name: "8", lotId: 1 },
      { name: "7", lotId: 1 },
      { name: "6", lotId: 1 },
      { name: "5", lotId: 1 },
      { name: "4", lotId: 1 },
      { name: "3", lotId: 1 },
      { name: "2", lotId: 1 },
      { name: "1", lotId: 1 },
    ],
  });

  console.log({
    createCarriers,
    createCategories,
    createPlant,
    createViews,
    createDocks,
    createLots,
    createSpots,
  });
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
